## **Install Quantum and Torch Requirements**

In [ ]:
!pip install pennylane pennylane-qiskit qiskit-aer torch torchvision numpy pandas matplotlib scipy

Collecting pennylane
  Downloading pennylane-0.45.0-py3-none-any.whl.metadata (10 kB)
Collecting pennylane-qiskit
  Downloading pennylane_qiskit-0.45.0-py3-none-any.whl.metadata (7.3 kB)
Collecting qiskit-aer
  Downloading qiskit_aer-0.17.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.26.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pennylane) (3.6.1)
Collecting rustworkx>=0.14.0 (from pennylane)
  Downloading rustworkx-0.18.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (10 kB)
Requirement already satisfied: autograd in /usr/local/lib/python3.12/dist-packages (from pennylane) (1.8.0)
Collecting appdirs (from pennylane)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting autoray==0.8.4 (from pennylane)
  Downloading autoray-0.8.4-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from pennylane) (6.2.6)
Collecting pennylane-lightning>=0.45 (from pennylane)
  Downloading pennylane_lightning-0.45.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pennylane) (2.32.4)
Requirement already satisfied: tomlkit in /usr/local/lib/python3.12/dist-packages (from pennylane) (0.13.3)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from pennylane) (4.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from pennylane) (26.2)
Collecting diastatic-malt (from pennylane)
  Downloading diastatic_malt-2.15.3-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: gast in /usr/local/lib/python3.12/dist-packages (from pennylane) (0.7.0)
Collecting qiskit<=2.3.0,>=2.0.0 (from pennylane-qiskit)
  Downloading qiskit-2.3.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (12 kB)
Collecting qiskit-ibm-runtime~=0.45.0 (from pennylane-qiskit)
  Downloading qiskit_ibm_runtime-0.45.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from pennylane-qiskit) (1.14.0)
Requirement already satisfied: psutil>=5 in /usr/local/lib/python3.12/dist-packages (from qiskit-aer) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from qiskit-aer) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Collecting scipy-openblas32>=0.3.26 (from pennylane-lightning>=0.45->pennylane)
  Downloading scipy_openblas32-0.3.33.112.0-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->qiskit-aer) (1.17.0)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.12/dist-packages (from qiskit<=2.3.0,>=2.0.0->pennylane-qiskit) (0.3.8)
Collecting stevedore>=3.0.0 (from qiskit<=2.3.0,>=2.0.0->pennylane-qiskit)
  Downloading stevedore-5.8.0-py3-none-any.whl.metadata (2.3 kB)
Collecting requests-ntlm>=1.1.0 (from qiskit-ibm-runtime~=0.45.0->pennylane-qiskit)
  Downloading requests_ntlm-1.3.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (2.5.0)
Collecting ibm-platform-services>=0.22.6 (from qiskit-ibm-runtime~=0.45.0->pennylane-qiskit)
  Downloading ibm_platform_services-0.75.1-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: pydantic>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (2.12.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pennylane) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pennylane) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pennylane) (2026.5.20)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->pennylane-qiskit) (1.3.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from diastatic-malt->pennylane) (3.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Collecting ibm_cloud_sdk_core<4.0.0,>=3.24.4 (from ibm-platform-services>=0.22.6->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit)
  Downloading ibm_cloud_sdk_core-3.24.4-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (0.4.2)
Requirement already satisfied: cryptography>=1.3 in /usr/local/lib/python3.12/dist-packages (from requests-ntlm>=1.1.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (48.0.1)
Collecting pyspnego>=0.4.0 (from requests-ntlm>=1.1.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit)
  Downloading pyspnego-0.12.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (2.0.0)
Requirement already satisfied: PyJWT<3.0.0,>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from ibm_cloud_sdk_core<4.0.0,>=3.24.4->ibm-platform-services>=0.22.6->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (2.13.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibm-runtime~=0.45.0->pennylane-qiskit) (3.0)
Downloading pennylane-0.45.0-py3-none-any.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 12.8 MB/s eta 0:00:00
Downloading autoray-0.8.4-py3-none-any.whl (937 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 937.5/937.5 kB 12.6 MB/s eta 0:00:00
Downloading pennylane_qiskit-0.45.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 3.0 MB/s eta 0:00:00
Downloading qiskit_aer-0.17.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 17.7 MB/s eta 0:00:00
Downloading pennylane_lightning-0.45.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (25.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.5/25.5 MB 20.9 MB/s eta 0:00:00
Downloading qiskit-2.3.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 31.6 MB/s eta 0:00:00
Downloading qiskit_ibm_runtime-0.45.1-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 27.1 MB/s eta 0:00:00
Downloading rustworkx-0.18.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 30.4 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading diastatic_malt-2.15.3-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.2/167.2 kB 12.4 MB/s eta 0:00:00
Downloading ibm_platform_services-0.75.1-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.9/386.9 kB 19.1 MB/s eta 0:00:00
Downloading requests_ntlm-1.3.0-py3-none-any.whl (6.6 kB)
Downloading scipy_openblas32-0.3.33.112.0-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 31.6 MB/s eta 0:00:00
Downloading stevedore-5.8.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 4.0 MB/s eta 0:00:00
Downloading ibm_cloud_sdk_core-3.24.4-py3-none-any.whl (75 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.8/75.8 kB 5.3 MB/s eta 0:00:00
Downloading pyspnego-0.12.1-py3-none-any.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 9.7 MB/s eta 0:00:00
Installing collected packages: appdirs, stevedore, scipy-openblas32, rustworkx, diastatic-malt, autoray, qiskit, ibm_cloud_sdk_core, qiskit-aer, pyspnego, ibm-platform-services, requests-ntlm, qiskit-ibm-runtime, pennylane-lightning, pennylane, pennylane-qiskit
Successfully installed appdirs-1.4.4 autoray-0.8.4 diastatic-malt-2.15.3 ibm-platform-services-0.75.1 ibm_cloud_sdk_core-3.24.4 pennylane-0.45.0 pennylane-lightning-0.45.0 pennylane-qiskit-0.45.0 pyspnego-0.12.1 qiskit-2.3.0 qiskit-aer-0.17.2 qiskit-ibm-runtime-0.45.1 requests-ntlm-1.3.0 rustworkx-0.18.0 scipy-openblas32-0.3.33.112.0 stevedore-5.8.0

## **Load In Water Desalienation and Flux Dataset**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Unzip
from zipfile import ZipFile

zip_file_path = "/content/drive/MyDrive/archive.zip"
target_directory = "UF pre-treatment of seawater RO feedwater - performance data"

with ZipFile(zip_file_path, 'r') as zip_object:
    zip_object.extractall()

In [ ]:
# Load in an example csv and .head()
import pandas as pd

df = pd.read_csv("/content/data in UF-RO system/training/20120308.csv")
df.head()

              Time Time Elapsed  ...   VFD-100-FB     TE/TT-100
0            Stamp        (sec)  ...          RPM         deg_C
1  41082.374017040  0.000000000  ...  0.240659505  16.519839540
2  41082.374028615  1.000000000  ...  0.246543601  16.523862854
3  41082.374040190  2.000000000  ...  0.246177591  16.522228383
4  41082.374051764  3.000000000  ...  0.233662479  16.526167877

[5 rows x 18 columns]

In [ ]:
df.isna().sum()

Time            0
Time Elapsed    0
FE/FT-100       0
FE/FT-101       0
FE/FT-102       0
FE/FT-103       0
FE/FT-104       0
pH/pHT-100      0
ORP/ORPT-100    0
PT-100          0
PT-101          0
PT-102          0
PT-103          0
PT-104          0
PT-100x         0
Tu/TuT-100      0
VFD-100-FB      0
TE/TT-100       0
dtype: int64

In [ ]:
df.columns

Index(['Time', 'Time Elapsed', 'FE/FT-100', 'FE/FT-101', 'FE/FT-102',
       'FE/FT-103', 'FE/FT-104', 'pH/pHT-100', 'ORP/ORPT-100', 'PT-100',
       'PT-101', 'PT-102', 'PT-103', 'PT-104', 'PT-100x', 'Tu/TuT-100',
       'VFD-100-FB', 'TE/TT-100'],
      dtype='object')

In [ ]:
df2= pd.read_csv("/content/data in UF-RO system/training/20120623.csv")
df2.head()

/tmp/ipykernel_1567/4211565958.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df2= pd.read_csv("/content/data in UF-RO system/training/20120623.csv")

,Time,Time Elapsed,FE/FT-100,FE/FT-101,FE/FT-102,FE/FT-103,FE/FT-104,pH/pHT-100,ORP/ORPT-100,PT-100,PT-101,PT-102,PT-103,PT-104,PT-100x,Tu/TuT-100,VFD-100-FB,TE/TT-100
0,Stamp,(sec),GPM,GPM,GPM,GPM,GPM,pH,mV,PSIG,PSIG,PSIG,PSIG,PSI,PSIG,NTU,RPM,deg_C
1,41083.419503147,0.000000000,29.415861714,0.080857387,0.034657203,0.000000000,0.006142040,1.117782775,-1750.011175871,10.850023170,5.670460842,4.924393890,5.903899897,0.582199323,1.945548244,-2.499990687,0.243853942,18.671753481
2,41083.419514721,1.000000000,29.450572153,0.005110323,-0.000903207,0.000000000,0.006096219,-0.297137428,-1750.032829121,10.530111334,5.847755556,5.146886044,5.908470444,0.573923137,2.094159247,-2.500013970,0.238959841,18.661611378
3,41083.419526296,2.000000000,29.586431628,0.008280964,0.000612241,0.000000000,0.006222226,-0.343401343,-1750.032829121,10.421058059,5.917465051,5.222526801,5.885303701,1.100012137,1.851987380,-2.500060536,0.257998869,18.673108555
4,41083.419537871,3.000000000,29.656101029,0.005253225,-0.002513371,0.000000000,0.007150103,-0.346775059,-1750.000698492,10.477813497,5.994369013,5.216625749,5.901911185,1.142092958,2.111046861,-2.499981374,0.251330599,18.660982735

## **Training Columns**
- Time Tracking: Time Elapsed (essential for tracking how long the system has been running/fouling).

- Flow Telemetry: FE/FT-100, FE/FT-101, FE/FT-102, FE/FT-103, FE/FT-104 (tracks fluid mass movement).

- Water Quality Metrics: pH/pHT-100, ORP/ORPT-100, Tu/TuT-100 (chemical traits and particle cloudiness causing membrane resistance).

- Thermal Dynamics: TE/TT-100 (tracks water temperature and fluid viscosity).

- Pump Mechanics: VFD-100-FB (the motor feedback state).

## **Testing Columns**
- Predicting the exact pressure required to push water through the filter matrix based entirely on the fluid's current chemical, thermal, and flow state: PT-100

In [ ]:
# Separate your features (environmental/operational states) from your optimization target (PT-100)
feature_cols = [
    'Time Elapsed', 'pH/pHT-100', 'ORP/ORPT-100', 'TE/TT-100',
    'Tu/TuT-100', 'FE/FT-100', 'FE/FT-101', 'FE/FT-102', 'FE/FT-103', 'FE/FT-104'
]

target_col = "PT-100"

In [ ]:
# Drop row 0
df = df.drop(0)
df.head()

              Time Time Elapsed  ...   VFD-100-FB     TE/TT-100
1  41082.374017040  0.000000000  ...  0.240659505  16.519839540
2  41082.374028615  1.000000000  ...  0.246543601  16.523862854
3  41082.374040190  2.000000000  ...  0.246177591  16.522228383
4  41082.374051764  3.000000000  ...  0.233662479  16.526167877
5  41082.374063339  4.000000000  ...  0.243177801  16.522940844

[5 rows x 18 columns]

## **Cross Fold Validation to prevent overfitting & Standard Scaler to Ensure Hybrid QNN Reads It Correctly**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import torch

# ==============================
# 1. SPLIT + SCALE CORRECTLY
# ==============================

X = df[feature_cols]
y = df[[target_col]]

x_scaler = StandardScaler()
y_scaler = StandardScaler()

X = x_scaler.fit_transform(X)
y = y_scaler.fit_transform(y)

"""tscv = TimeSeriesSplit(n_splits=5)

for fold, (train_index, test_index) in enumerate(tscv.split(X)):
    X_train_raw, X_test_raw = X[train_index], X[test_index]
    y_train_raw, y_test_raw = y[train_index], y[test_index]

    x_scaler = StandardScaler()
    y_scaler = StandardScaler()

    X_train = x_scaler.fit_transform(X_train_raw)
    X_test = x_scaler.transform(X_test_raw)

    y_train = y_scaler.fit_transform(y_train_raw)
    y_test = y_scaler.transform(y_test_raw)

# Use normal train test split for now"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_t = torch.tensor(X_train, dtype=torch.float32)
X_test_t = torch.tensor(X_test, dtype=torch.float32)

y_train_t = torch.tensor(y_train, dtype=torch.float32)
y_test_t = torch.tensor(y_test, dtype=torch.float32)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pennylane as qml
import numpy as np

# ==========================================
# 1. Quantum Topology Setup
# ==========================================
n_qubits = 4
q_layers = 3

# Native simulators for rapid gradient computation
dev1 = qml.device("default.qubit", wires=n_qubits)
dev2 = qml.device("default.qubit", wires=n_qubits)

@qml.qnode(dev1, interface="torch")
def quantum_vqc(inputs, weights):
    qml.templates.AngleEmbedding(inputs, wires=range(n_qubits), rotation='X')
    qml.templates.StronglyEntanglingLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]

@qml.qnode(dev2, interface="torch")
def quantum_vqc2(inputs, weights):
    qml.templates.AngleEmbedding(inputs, wires=range(n_qubits), rotation='X')
    qml.templates.StronglyEntanglingLayers(weights, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]


# ==========================================
# 2. SOTA CLASSICAL COMPONENTS
# ==========================================
class GatedResidualBlock(nn.Module):
    def __init__(self, input_dim, output_dim, dropout=0.1):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, output_dim)
        self.linear2 = nn.Linear(output_dim, output_dim)
        self.gate = nn.Linear(output_dim, output_dim)
        self.dropout = nn.Dropout(dropout)

        # Match dimensions for skip connection if needed
        self.skip = nn.Linear(input_dim, output_dim) if input_dim != output_dim else nn.Identity()

    def forward(self, x):
        residual = self.skip(x)
        x = torch.relu(self.linear1(x))
        x = self.dropout(x)
        x = self.linear2(x)
        # Gated Linear Unit activation mechanism
        x = x * torch.sigmoid(self.gate(x))
        return x + residual


# ==========================================
# 3. ENTIRE HYBRID NETWORK ARCHITECTURE
# ==========================================
class EndToEndParallelQNN(nn.Module):
    def __init__(self, input_dim=11, output_dim=1):
        super().__init__()

        # Classical Front-End: Process and condense incoming water telemetry
        self.encoder = nn.Sequential(
            GatedResidualBlock(input_dim, 32),
            GatedResidualBlock(32, 16)
        )

        # Mid-splitting: Map representation vector to two distinct quantum feature-heads
        self.to_q1 = nn.Linear(16, n_qubits)
        self.to_q2 = nn.Linear(16, n_qubits)

        # PennyLane Quantum Layers wrapped for PyTorch autograd
        weight_shapes = {"weights": (q_layers, n_qubits, 3)}
        self.qlayer1 = qml.qnn.TorchLayer(quantum_vqc, weight_shapes)
        self.qlayer2 = qml.qnn.TorchLayer(quantum_vqc2, weight_shapes)

        # Classical Back-End: Fuse the expectation values from both circuits
        self.decoder = nn.Sequential(
            GatedResidualBlock(n_qubits * 2, 16),
            nn.Linear(16, output_dim)
        )

    def forward(self, x):
        # Step 1: Classical encoding
        features = self.encoder(x)

        # Step 2: Route features into distinct quantum heads, bounded to [-pi, pi]
        q1_in = torch.tanh(self.to_q1(features)) * np.pi
        q2_in = torch.tanh(self.to_q2(features)) * np.pi

        # Step 3: Run Quantum Circuits
        q1_out = self.qlayer1(q1_in)
        q2_out = self.qlayer2(q2_in)

        # Step 4: Concatenate quantum outputs (Shape: Batch, n_qubits * 2)
        combined_quantum_states = torch.cat((q1_out, q2_out), dim=1)

        # Step 5: Final output regression mapping (PT-100)
        return self.decoder(combined_quantum_states)


# Build standard PyTorch DataLoaders
train_dataset = TensorDataset(X_train_t, y_train_t)
test_dataset = TensorDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)


# ==========================================
# 5. EXECUTION: THE TRAIN & EVALUATION LOOP
# ==========================================
# The input_dim should match the number of features in X_train_t
model = EndToEndParallelQNN(input_dim=X_train_t.shape[1], output_dim=1)
criterion = nn.MSELoss()
optimizer = optim.AdamW(model.parameters(), lr=0.01, weight_decay=0.01)

epochs = 5
print("🚀 Starting Hybrid Quantum-Classical Training Loop...\n")

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()

        # Forward pass through whole pipeline
        predictions = model(batch_X)
        loss = criterion(predictions, batch_y)

        # Backpropagate gradients across classical and quantum nodes
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)

    epoch_loss = running_loss / len(train_loader.dataset)
    print(f"Epoch [{epoch+1}/{epochs}] - Training MSE Loss: {epoch_loss:.5f}")

# ==========================================
# 6. MODEL VALIDATION / TESTING PHASE
# ==========================================
model.eval()
test_loss = 0.0

print("\n Entering Validation Phase...")
with torch.no_grad():
    for batch_X, batch_y in test_loader:
        test_preds = model(batch_X)
        loss = criterion(test_preds, batch_y)
        test_loss += loss.item() * batch_X.size(0)

final_test_mse = test_loss / len(test_loader.dataset)
print(f" Final Out-of-Sample Test MSE: {final_test_mse:.5f}")
print("\n Pipeline execution complete! Ready to swap in your real CSV tensors.")

🚀 Starting Hybrid Quantum-Classical Training Loop...

Epoch [1/5] - Training MSE Loss: 0.06833
Epoch [2/5] - Training MSE Loss: 0.04899
Epoch [3/5] - Training MSE Loss: 0.12419
Epoch [4/5] - Training MSE Loss: 0.13385
Epoch [5/5] - Training MSE Loss: 0.11610

 Entering Validation Phase...
 Final Out-of-Sample Test MSE: 0.10944

 Pipeline execution complete! Ready to swap in your real CSV tensors.

**Anlysis: Due to Standard Scaling, a MSE of ~0.05 is roughly 0.5 off on Pressure (PSIG (Pounds per Square Inch Gauge))**

In [ ]:
# Save the model
torch.save(model.state_dict(), 'hybrid_qnn_model_PT100.pth')

## **Load in Water Leak Dataset**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import torch
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pennylane as qml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Load in Water Leak Detection Dataset
df_water_leak = pd.read_csv("/content/water_leak_detection_1000_rows.csv")
df_water_leak.head()

,Timestamp,Sensor_ID,Pressure (bar),Flow Rate (L/s),Temperature (°C),Leak Status,Burst Status
0,2024-01-01 00:00:00,S007,3.694814,77.515218,21.695365,0,0
1,2024-01-01 00:05:00,S007,2.587125,179.926422,19.016725,0,0
2,2024-01-01 00:10:00,S002,2.448965,210.130823,10.011681,1,0
3,2024-01-01 00:15:00,S009,2.936844,141.777934,12.092408,0,0
4,2024-01-01 00:20:00,S003,3.073693,197.484633,17.001443,0,0

In [ ]:
df_water_leak.isna().sum()

Timestamp           0
Sensor_ID           0
Pressure (bar)      0
Flow Rate (L/s)     0
Temperature (°C)    0
Leak Status         0
Burst Status        0
dtype: int64

In [ ]:
# Feature Engineering: Compute Delta Pressure (bar), Flow Rate (L/s), Temperature (Degree Celsius)
df_water_leak['Delta Pressure (bar)'] = df_water_leak['Pressure (bar)'].diff()
df_water_leak['Flow Rate Delta (L/s)'] = (df_water_leak['Flow Rate (L/s)'] / 60).diff()
df_water_leak['Temperature Delta (°C)'] = df_water_leak['Temperature (°C)'].diff()

In [ ]:
df_water_leak.head()

,Timestamp,Sensor_ID,Pressure (bar),Flow Rate (L/s),Temperature (°C),Leak Status,Burst Status,Delta Pressure (bar),Flow Rate Delta (L/s),Temperature Delta (°C)
0,2024-01-01 00:00:00,S007,3.694814,77.515218,21.695365,0,0,NaN,NaN,NaN
1,2024-01-01 00:05:00,S007,2.587125,179.926422,19.016725,0,0,-1.107689,1.706853,-2.678640
2,2024-01-01 00:10:00,S002,2.448965,210.130823,10.011681,1,0,-0.138161,0.503407,-9.005044
3,2024-01-01 00:15:00,S009,2.936844,141.777934,12.092408,0,0,0.487879,-1.139215,2.080726
4,2024-01-01 00:20:00,S003,3.073693,197.484633,17.001443,0,0,0.136849,0.928445,4.909035

In [ ]:
df_water_leak.isna().sum()

Timestamp                 0
Sensor_ID                 0
Pressure (bar)            0
Flow Rate (L/s)           0
Temperature (°C)          0
Leak Status               0
Burst Status              0
Delta Pressure (bar)      1
Flow Rate Delta (L/s)     1
Temperature Delta (°C)    1
dtype: int64

In [ ]:
# Impute NaNs with average (Flow Rate), Temperature, and Pressure
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
df_water_leak[['Flow Rate Delta (L/s)', 'Temperature Delta (°C)', 'Delta Pressure (bar)']] = imputer.fit_transform(df_water_leak[['Flow Rate (L/s)', 'Temperature (°C)', 'Pressure (bar)']])

In [ ]:
df_water_leak.isna().sum()

Timestamp                 0
Sensor_ID                 0
Pressure (bar)            0
Flow Rate (L/s)           0
Temperature (°C)          0
Leak Status               0
Burst Status              0
Delta Pressure (bar)      0
Flow Rate Delta (L/s)     0
Temperature Delta (°C)    0
dtype: int64

In [ ]:
df_water_leak.head()

                    Sensor_ID  ...  Temperature Delta (°C)
Timestamp                      ...
2024-01-01 00:00:00      S007  ...                     NaN
2024-01-01 00:05:00      S007  ...                     NaN
2024-01-01 00:10:00      S002  ...                     NaN
2024-01-01 00:15:00      S009  ...                     NaN
2024-01-01 00:20:00      S003  ...               15.963525

[5 rows x 9 columns]

In [ ]:
leak_burst_features = ['Pressure (bar)', 'Flow Rate (L/s)', 'Delta_Pressure', 'Delta_Flow', 'Temperature (°C)', 'Anomaly Score']

In [ ]:
df_water_leak.columns

Index(['Sensor_ID', 'Pressure (bar)', 'Flow Rate (L/s)', 'Temperature (°C)',
       'Leak Status', 'Burst Status', 'Flow Rate Delta (L/s)',
       'Temperature Delta (°C)', 'Delta Pressure (bar)'],
      dtype='object')

In [ ]:
# Transform Timestamp into rolling means
df_water_leak['Timestamp'] = pd.to_datetime(df_water_leak['Timestamp'])
df_water_leak.set_index('Timestamp', inplace=True)

# All numerical columns to be roling meaned instead of just the original column names
df_water_leak_numerical = df_water_leak.select_dtypes(include=['float64', 'int64'])
rolling_means = df_water_leak_numerical.rolling(window=5).mean()

In [ ]:
rolling_means.head()

                     Pressure (bar)  ...  Temperature Delta (°C)
Timestamp                            ...
2024-01-01 00:00:00             NaN  ...                     NaN
2024-01-01 00:05:00             NaN  ...                     NaN
2024-01-01 00:10:00             NaN  ...                     NaN
2024-01-01 00:15:00             NaN  ...                     NaN
2024-01-01 00:20:00        2.948288  ...               15.963525

[5 rows x 8 columns]

In [ ]:
# Rename rolling_means columns to have a {rolling_5}
rolling_means.columns = [f"{col}_rolling_5" for col in rolling_means.columns]

In [ ]:
rolling_means.head()

                     Pressure (bar)_rolling_5  ...  Temperature Delta (°C)_rolling_5
Timestamp                                      ...
2024-01-01 00:00:00                       NaN  ...                               NaN
2024-01-01 00:05:00                       NaN  ...                               NaN
2024-01-01 00:10:00                       NaN  ...                               NaN
2024-01-01 00:15:00                       NaN  ...                               NaN
2024-01-01 00:20:00                  2.948288  ...                         15.963525

[5 rows x 8 columns]

In [ ]:
df_water_leak_numerical.head()

                     Pressure (bar)  ...  Temperature Delta (°C)
Timestamp                            ...
2024-01-01 00:00:00        3.694814  ...               21.695365
2024-01-01 00:05:00        2.587125  ...               19.016725
2024-01-01 00:10:00        2.448965  ...               10.011681
2024-01-01 00:15:00        2.936844  ...               12.092408
2024-01-01 00:20:00        3.073693  ...               17.001443

[5 rows x 8 columns]

In [ ]:
# Apply rolling means back to df_water_leak.
# Later Found Out Rolling Mean Columns Add Too Much Noise to Quantum Hybrid Neural Networks
# df_water_leak[rolling_means.columns] = rolling_means

In [ ]:
df_water_leak.head()

,Sensor_ID,Pressure (bar),Flow Rate (L/s),Temperature (°C),Leak Status,Burst Status,Delta Pressure (bar),Flow Rate Delta (L/s),Temperature Delta (°C)
Timestamp,,,,,,,,,
2024-01-01 00:00:00,S007,3.694814,77.515218,21.695365,0,0,3.694814,77.515218,21.695365
2024-01-01 00:05:00,S007,2.587125,179.926422,19.016725,0,0,2.587125,179.926422,19.016725
2024-01-01 00:10:00,S002,2.448965,210.130823,10.011681,1,0,2.448965,210.130823,10.011681
2024-01-01 00:15:00,S009,2.936844,141.777934,12.092408,0,0,2.936844,141.777934,12.092408
2024-01-01 00:20:00,S003,3.073693,197.484633,17.001443,0,0,3.073693,197.484633,17.001443

In [ ]:
df_water_leak.columns

Index(['Sensor_ID', 'Pressure (bar)', 'Flow Rate (L/s)', 'Temperature (°C)',
       'Leak Status', 'Burst Status', 'Delta Pressure (bar)',
       'Flow Rate Delta (L/s)', 'Temperature Delta (°C)',
       'Pressure (bar)_rolling_5', 'Flow Rate (L/s)_rolling_5',
       'Temperature (°C)_rolling_5', 'Leak Status_rolling_5',
       'Burst Status_rolling_5', 'Delta Pressure (bar)_rolling_5',
       'Flow Rate Delta (L/s)_rolling_5', 'Temperature Delta (°C)_rolling_5'],
      dtype='object')

In [ ]:
# Drop Sensor ID (it'll just Add noise, already captures the data, only necessary if one sensor is off or special)
df_water_leak.drop(columns=['Sensor_ID'], inplace=True)

In [ ]:
df_water_leak.head()

,Pressure (bar),Flow Rate (L/s),Temperature (°C),Leak Status,Burst Status,Delta Pressure (bar),Flow Rate Delta (L/s),Temperature Delta (°C)
Timestamp,,,,,,,,
2024-01-01 00:00:00,3.694814,77.515218,21.695365,0,0,3.694814,77.515218,21.695365
2024-01-01 00:05:00,2.587125,179.926422,19.016725,0,0,2.587125,179.926422,19.016725
2024-01-01 00:10:00,2.448965,210.130823,10.011681,1,0,2.448965,210.130823,10.011681
2024-01-01 00:15:00,2.936844,141.777934,12.092408,0,0,2.936844,141.777934,12.092408
2024-01-01 00:20:00,3.073693,197.484633,17.001443,0,0,3.073693,197.484633,17.001443

In [ ]:
# Standardize the delta temperature and all numerical columns
# df_clean = df_water_leak.dropna(subset=['Pressure (bar)_rolling_5', 'Flow Rate Delta (L/s)_rolling_5']).copy()

In [ ]:
df_clean.head()

                     Pressure (bar)  ...  Temperature Delta (°C)_rolling_5
Timestamp                            ...
2024-01-01 00:20:00        3.073693  ...                         15.963525
2024-01-01 00:25:00        2.597577  ...                         16.521348
2024-01-01 00:30:00        2.846341  ...                         16.767793
2024-01-01 00:35:00        3.863981  ...                         18.753024
2024-01-01 00:40:00        3.351550  ...                         20.861397

[5 rows x 16 columns]

In [ ]:
df_clean = df_water_leak.copy()

In [ ]:
df_clean.isna().sum()

Pressure (bar)            0
Flow Rate (L/s)           0
Temperature (°C)          0
Leak Status               0
Burst Status              0
Delta Pressure (bar)      0
Flow Rate Delta (L/s)     0
Temperature Delta (°C)    0
dtype: int64

In [ ]:
# Select your independent, non-cheating structural variables
feature_cols = [col for col in df_clean.columns if col not in ['Leak Status', 'Burst Status']]

X_raw = df_clean[feature_cols]
y_leak_raw = df_clean['Leak Status']
y_burst_raw = df_clean['Burst Status']

In [ ]:
X_raw

,Pressure (bar),Flow Rate (L/s),Temperature (°C),Delta Pressure (bar),Flow Rate Delta (L/s),Temperature Delta (°C)
Timestamp,,,,,,
2024-01-01 00:00:00,3.694814,77.515218,21.695365,3.694814,77.515218,21.695365
2024-01-01 00:05:00,2.587125,179.926422,19.016725,2.587125,179.926422,19.016725
2024-01-01 00:10:00,2.448965,210.130823,10.011681,2.448965,210.130823,10.011681
2024-01-01 00:15:00,2.936844,141.777934,12.092408,2.936844,141.777934,12.092408
2024-01-01 00:20:00,3.073693,197.484633,17.001443,3.073693,197.484633,17.001443
...,...,...,...,...,...,...
2024-01-04 10:55:00,2.949811,55.160481,19.523946,2.949811,55.160481,19.523946
2024-01-04 11:00:00,3.836533,172.041322,20.724292,3.836533,172.041322,20.724292
2024-01-04 11:05:00,2.716468,64.033911,10.250073,2.716468,64.033911,10.250073
2024-01-04 11:10:00,3.017897,75.913513,19.329712,3.017897,75.913513,19.329712
2024-01-04 11:15:00,3.777372,179.568443,16.101606,3.777372,179.568443,16.101606

In [ ]:
# Standardize and scale
x_scaler = StandardScaler()

X = x_scaler.fit_transform(X_raw)

# Train test split X raw with y leak raw
X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(X, y_leak_raw, test_size=0.2, random_state=42)

In [ ]:
y_train_raw

Timestamp
2024-01-01 02:25:00    0
2024-01-02 20:35:00    0
2024-01-03 09:55:00    0
2024-01-02 22:25:00    0
2024-01-03 21:40:00    0
                      ..
2024-01-01 08:50:00    0
2024-01-01 22:30:00    0
2024-01-03 23:40:00    0
2024-01-02 12:15:00    0
2024-01-01 08:30:00    0
Name: Leak Status, Length: 800, dtype: int64

In [ ]:
# Transform X

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pennylane as qml
import numpy as np

n_qubits = 4
q_layers = 2

X_train_raw = torch.tensor(X_train_raw, dtype=torch.float32)
y_train_raw = torch.tensor(y_train_raw, dtype=torch.long)

X_test_raw = torch.tensor(X_test_raw, dtype=torch.float32)
y_test_raw = torch.tensor(y_test_raw, dtype=torch.long)

train_dataset = TensorDataset(X_train_raw, y_train_raw)
test_dataset = TensorDataset(X_test_raw, y_test_raw)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

/tmp/ipykernel_12708/3251212445.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_raw = torch.tensor(X_train_raw, dtype=torch.float32)
/tmp/ipykernel_12708/3251212445.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_raw = torch.tensor(y_train_raw, dtype=torch.long)
/tmp/ipykernel_12708/3251212445.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_raw = torch.tensor(X_test_raw, dtype=torch.float32)
/tmp/ipykernel_12708/3251212445.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_raw = torch.tensor(y_test_raw, dtype=torch.long)

In [ ]:
n_qubits = 4
q_layers = 2  # Dropped from 3 to 2 to drastically reduce Barren Plateau risk

dev1 = qml.device("default.qubit", wires=n_qubits)
dev2 = qml.device("default.qubit", wires=n_qubits)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pennylane as qml
import numpy as np

# ==========================================
# 1. STABILIZED QUANTUM TOPOLOGY
# ==========================================
n_qubits = 4
q_layers = 2

dev1 = qml.device("default.qubit", wires=n_qubits)
dev2 = qml.device("default.qubit", wires=n_qubits)

def vqc_base(inputs, weights):
    # Initial data angle mapping
    qml.templates.AngleEmbedding(inputs, wires=range(n_qubits), rotation='Y')

    # First variational entangling layer block
    qml.templates.StronglyEntanglingLayers(weights[0], wires=range(n_qubits))

    # Internal mid-circuit entanglement routing
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.CNOT(wires=[2, 3])

    # Final variational processing layer block
    qml.templates.StronglyEntanglingLayers(weights[1], wires=range(n_qubits))

    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]

qnode1 = qml.QNode(vqc_base, dev1, interface="torch")
qnode2 = qml.QNode(vqc_base, dev2, interface="torch")


# ==========================================
# 2. SOTA ATTENTION & RESIDUAL BLOCKS
# ==========================================
class HydroFeatureAttention(nn.Module):
    """Computes self-attention across tabular water features to emphasize anomalies."""
    def __init__(self, num_features, head_dim=1):
        super().__init__()
        self.num_features = num_features
        self.head_dim = head_dim

        self.query_proj = nn.Linear(1, head_dim)
        self.key_proj   = nn.Linear(1, head_dim)
        self.value_proj = nn.Linear(1, head_dim)
        self.scale = np.sqrt(head_dim)
        self.output_proj = nn.Linear(head_dim, 1)

    def forward(self, x):
        x_reshaped = x.unsqueeze(-1) # (batch_size, num_features, 1)

        q = self.query_proj(x_reshaped)
        k = self.key_proj(x_reshaped)
        v = self.value_proj(x_reshaped)

        attn_scores = torch.softmax((q @ k.transpose(-2, -1)) / self.scale, dim=-1)
        attention_output = attn_scores @ v

        output = self.output_proj(attention_output).squeeze(-1)
        return output


class GatedResidualBlock(nn.Module):
    def __init__(self, input_dim, output_dim, dropout=0.3):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, output_dim)
        self.linear2 = nn.Linear(output_dim, output_dim)
        self.gate = nn.Linear(output_dim, output_dim)
        self.dropout = nn.Dropout(dropout)

        # Using exact nn.Identity mapping for uniform feature dimension paths
        self.skip = nn.Identity() if input_dim == output_dim else nn.Linear(input_dim, output_dim)

    def forward(self, x):
        residual = self.skip(x)
        x_act = torch.relu(self.linear1(x))
        x_act = self.dropout(x_act)
        x_act = self.linear2(x_act)
        x_act = x_act * torch.sigmoid(self.gate(x_act))
        return x_act + residual


# ==========================================
# 3. END-TO-END ADVANCED CLASSIFIER ARCHITECTURE
# ==========================================
class QuantumAttentionInfrastructureGuard(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        self.attention = HydroFeatureAttention(num_features=input_dim)

        self.encoder = nn.Sequential(
            GatedResidualBlock(input_dim, 32, dropout=0.3),
            GatedResidualBlock(32, 16, dropout=0.3)
        )

        self.to_q1 = nn.Linear(16, n_qubits)
        self.to_q2 = nn.Linear(16, n_qubits)
        self.quantum_dropout = nn.Dropout(p=0.2)

        # Correct shape assignment for our custom two-tier block circuit weights
        # Shape: (2 blocks, q_layers, n_qubits, 3 rotation dimensions)
        weight_shapes = {"weights": (2, q_layers, n_qubits, 3)}
        self.qlayer1 = qml.qnn.TorchLayer(qnode1, weight_shapes)
        self.qlayer2 = qml.qnn.TorchLayer(qnode2, weight_shapes)

        # STABLE UPGRADE: Removed Sigmoid() completely from the final layer block
        self.decoder = nn.Sequential(
            GatedResidualBlock(n_qubits * 2, 16, dropout=0.2),
            nn.Linear(16, 1)
        )

    def forward(self, x):
        x = self.attention(x)
        features = self.encoder(x)

        q1_in = torch.tanh(self.to_q1(features)) * np.pi
        q2_in = torch.tanh(self.to_q2(features)) * np.pi

        q1_in = self.quantum_dropout(q1_in)
        q2_in = self.quantum_dropout(q2_in)

        q1_out = self.qlayer1(q1_in)
        q2_out = self.qlayer2(q2_in)

        combined_quantum_signals = torch.cat((q1_out, q2_out), dim=1)
        return self.decoder(combined_quantum_signals)


# ==========================================
# 4. DATA LOADER PREPARATION
# ==========================================
input_features_count = X_train_raw.shape[1]


# ==========================================
# 5. EXECUTION: TWO-SPEED STABILIZED OPTIMIZER
# ==========================================
model = QuantumAttentionInfrastructureGuard(input_dim=input_features_count)

# HIGH STABILITY LOSS HEADER
criterion = nn.BCEWithLogitsLoss()

classical_params = []
quantum_params = []

for name, param in model.named_parameters():
    if "quantum_layer" in name or "qlayer" in name:
        quantum_params.append(param)
    else:
        classical_params.append(param)

optimizer = optim.AdamW([
    {'params': classical_params, 'lr': 0.005, 'weight_decay': 0.01},
    {'params': quantum_params, 'lr': 0.0005, 'weight_decay': 0.001}
])

epochs = 5
print("🚀 Launching Logit-Stabilized Quantum-Attention Training Loop...\n")

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()

        # Predictions here output raw unbounded logits
        predictions = model(batch_X)
        # Reshape batch_y to match predictions [batch_size, 1]
        loss = criterion(predictions, batch_y.unsqueeze(1).float())

        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)

    epoch_loss = running_loss / len(train_loader.dataset)
    print(f"Epoch [{epoch+1}/{epochs}] - Training Logit BCE Loss: {epoch_loss:.5f}")


# ==========================================
# 6. MODEL VALIDATION / EVALUATION
# ==========================================
model.eval()
test_loss = 0.0
correct_predictions = 0

print("\n🔒 Entering Validation Phase...")
with torch.no_grad():
    for batch_X, batch_y in test_loader:
        test_preds = model(batch_X)
        # Reshape batch_y to match predictions [batch_size, 1]
        loss = criterion(test_preds, batch_y.unsqueeze(1).float())
        test_loss += loss.item() * batch_X.size(0)

        # STABLE ACCURACY CHECK: Explicitly computing the Sigmoid boundary mapping
        binary_preds = (torch.sigmoid(test_preds) >= 0.5).float()
        correct_predictions += (binary_preds == batch_y.unsqueeze(1)).sum().item()

final_test_bce = test_loss / len(test_loader.dataset)
final_accuracy = (correct_predictions / len(test_loader.dataset)) * 100

print(f"➡️ Final Out-of-Sample Test Logit BCE Loss: {final_test_bce:.5f}")
print(f"➡️ Total Classification Accuracy: {final_accuracy:.2f}%")
print("\n✨ Process finished cleanly. Run this exact setup for Leak and Burst instances.")

🚀 Launching Logit-Stabilized Quantum-Attention Training Loop...

Epoch [1/5] - Training Logit BCE Loss: 0.35243
Epoch [2/5] - Training Logit BCE Loss: 0.09226
Epoch [3/5] - Training Logit BCE Loss: 0.07804
Epoch [4/5] - Training Logit BCE Loss: 0.07652
Epoch [5/5] - Training Logit BCE Loss: 0.06954

🔒 Entering Validation Phase...
➡️ Final Out-of-Sample Test Logit BCE Loss: 0.02966
➡️ Total Classification Accuracy: 99.00%

✨ Process finished cleanly. Run this exact setup for Leak and Burst instances.

In [ ]:
# Save the Leak detection model
torch.save(model.state_dict(), 'hybrid_qnn_model_leak_pressure_flow_temperature.pth')

In [ ]:
# Standardize and scale
x_scaler = StandardScaler()

X = x_scaler.fit_transform(X_raw)

# Train test split X raw with y leak raw
X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(X, y_burst_raw, test_size=0.2, random_state=42)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pennylane as qml
import numpy as np

n_qubits = 4
q_layers = 2

X_train_raw = torch.tensor(X_train_raw, dtype=torch.float32)
y_train_raw = torch.tensor(y_train_raw, dtype=torch.long)

X_test_raw = torch.tensor(X_test_raw, dtype=torch.float32)
y_test_raw = torch.tensor(y_test_raw, dtype=torch.long)

train_dataset = TensorDataset(X_train_raw, y_train_raw)
test_dataset = TensorDataset(X_test_raw, y_test_raw)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

/tmp/ipykernel_12708/3251212445.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y_train_raw = torch.tensor(y_train_raw, dtype=torch.long)
/tmp/ipykernel_12708/3251212445.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y_test_raw = torch.tensor(y_test_raw, dtype=torch.long)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pennylane as qml
import numpy as np

# ==========================================
# 1. STABILIZED QUANTUM TOPOLOGY
# ==========================================
n_qubits = 4
q_layers = 2

dev1 = qml.device("default.qubit", wires=n_qubits)
dev2 = qml.device("default.qubit", wires=n_qubits)

def vqc_base(inputs, weights):
    # Initial data angle mapping
    qml.templates.AngleEmbedding(inputs, wires=range(n_qubits), rotation='Y')

    # First variational entangling layer block
    qml.templates.StronglyEntanglingLayers(weights[0], wires=range(n_qubits))

    # Internal mid-circuit entanglement routing
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.CNOT(wires=[2, 3])

    # Final variational processing layer block
    qml.templates.StronglyEntanglingLayers(weights[1], wires=range(n_qubits))

    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]

qnode1 = qml.QNode(vqc_base, dev1, interface="torch")
qnode2 = qml.QNode(vqc_base, dev2, interface="torch")


# ==========================================
# 2. SOTA ATTENTION & RESIDUAL BLOCKS
# ==========================================
class HydroFeatureAttention(nn.Module):
    """Computes self-attention across tabular water features to emphasize anomalies."""
    def __init__(self, num_features, head_dim=1):
        super().__init__()
        self.num_features = num_features
        self.head_dim = head_dim

        self.query_proj = nn.Linear(1, head_dim)
        self.key_proj   = nn.Linear(1, head_dim)
        self.value_proj = nn.Linear(1, head_dim)
        self.scale = np.sqrt(head_dim)
        self.output_proj = nn.Linear(head_dim, 1)

    def forward(self, x):
        x_reshaped = x.unsqueeze(-1) # (batch_size, num_features, 1)

        q = self.query_proj(x_reshaped)
        k = self.key_proj(x_reshaped)
        v = self.value_proj(x_reshaped)

        attn_scores = torch.softmax((q @ k.transpose(-2, -1)) / self.scale, dim=-1)
        attention_output = attn_scores @ v

        output = self.output_proj(attention_output).squeeze(-1)
        return output


class GatedResidualBlock(nn.Module):
    def __init__(self, input_dim, output_dim, dropout=0.3):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, output_dim)
        self.linear2 = nn.Linear(output_dim, output_dim)
        self.gate = nn.Linear(output_dim, output_dim)
        self.dropout = nn.Dropout(dropout)

        # Using exact nn.Identity mapping for uniform feature dimension paths
        self.skip = nn.Identity() if input_dim == output_dim else nn.Linear(input_dim, output_dim)

    def forward(self, x):
        residual = self.skip(x)
        x_act = torch.relu(self.linear1(x))
        x_act = self.dropout(x_act)
        x_act = self.linear2(x_act)
        x_act = x_act * torch.sigmoid(self.gate(x_act))
        return x_act + residual


# ==========================================
# 3. END-TO-END ADVANCED CLASSIFIER ARCHITECTURE
# ==========================================
class QuantumAttentionInfrastructureGuard(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        self.attention = HydroFeatureAttention(num_features=input_dim)

        self.encoder = nn.Sequential(
            GatedResidualBlock(input_dim, 32, dropout=0.3),
            GatedResidualBlock(32, 16, dropout=0.3)
        )

        self.to_q1 = nn.Linear(16, n_qubits)
        self.to_q2 = nn.Linear(16, n_qubits)
        self.quantum_dropout = nn.Dropout(p=0.2)

        # Correct shape assignment for our custom two-tier block circuit weights
        # Shape: (2 blocks, q_layers, n_qubits, 3 rotation dimensions)
        weight_shapes = {"weights": (2, q_layers, n_qubits, 3)}
        self.qlayer1 = qml.qnn.TorchLayer(qnode1, weight_shapes)
        self.qlayer2 = qml.qnn.TorchLayer(qnode2, weight_shapes)

        # STABLE UPGRADE: Removed Sigmoid() completely from the final layer block
        self.decoder = nn.Sequential(
            GatedResidualBlock(n_qubits * 2, 16, dropout=0.2),
            nn.Linear(16, 1)
        )

    def forward(self, x):
        x = self.attention(x)
        features = self.encoder(x)

        q1_in = torch.tanh(self.to_q1(features)) * np.pi
        q2_in = torch.tanh(self.to_q2(features)) * np.pi

        q1_in = self.quantum_dropout(q1_in)
        q2_in = self.quantum_dropout(q2_in)

        q1_out = self.qlayer1(q1_in)
        q2_out = self.qlayer2(q2_in)

        combined_quantum_signals = torch.cat((q1_out, q2_out), dim=1)
        return self.decoder(combined_quantum_signals)


# ==========================================
# 4. DATA LOADER PREPARATION
# ==========================================
input_features_count = X_train_raw.shape[1]


# ==========================================
# 5. EXECUTION: TWO-SPEED STABILIZED OPTIMIZER
# ==========================================
model = QuantumAttentionInfrastructureGuard(input_dim=input_features_count)

# HIGH STABILITY LOSS HEADER
criterion = nn.BCEWithLogitsLoss()

classical_params = []
quantum_params = []

for name, param in model.named_parameters():
    if "quantum_layer" in name or "qlayer" in name:
        quantum_params.append(param)
    else:
        classical_params.append(param)

optimizer = optim.AdamW([
    {'params': classical_params, 'lr': 0.005, 'weight_decay': 0.01},
    {'params': quantum_params, 'lr': 0.0005, 'weight_decay': 0.001}
])

epochs = 10
print("🚀 Launching Logit-Stabilized Quantum-Attention Training Loop...\n")

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()

        # Predictions here output raw unbounded logits
        predictions = model(batch_X)
        # Reshape batch_y to match predictions [batch_size, 1]
        loss = criterion(predictions, batch_y.unsqueeze(1).float())

        loss.backward()
        optimizer.step()

        running_loss += loss.item() * batch_X.size(0)

    epoch_loss = running_loss / len(train_loader.dataset)
    print(f"Epoch [{epoch+1}/{epochs}] - Training Logit BCE Loss: {epoch_loss:.5f}")


# ==========================================
# 6. MODEL VALIDATION / EVALUATION
# ==========================================
model.eval()
test_loss = 0.0
correct_predictions = 0

print("\n🔒 Entering Validation Phase...")
with torch.no_grad():
    for batch_X, batch_y in test_loader:
        test_preds = model(batch_X)
        # Reshape batch_y to match predictions [batch_size, 1]
        loss = criterion(test_preds, batch_y.unsqueeze(1).float())
        test_loss += loss.item() * batch_X.size(0)

        # STABLE ACCURACY CHECK: Explicitly computing the Sigmoid boundary mapping
        binary_preds = (torch.sigmoid(test_preds) >= 0.5).float()
        correct_predictions += (binary_preds == batch_y.unsqueeze(1)).sum().item()

final_test_bce = test_loss / len(test_loader.dataset)
final_accuracy = (correct_predictions / len(test_loader.dataset)) * 100

print(f"➡️ Final Out-of-Sample Test Logit BCE Loss: {final_test_bce:.5f}")
print(f"➡️ Total Classification Accuracy: {final_accuracy:.2f}%")
print("\n✨ Process finished cleanly. Run this exact setup for Burst instances.")

🚀 Launching Logit-Stabilized Quantum-Attention Training Loop...

Epoch [1/10] - Training Logit BCE Loss: 0.28786
Epoch [2/10] - Training Logit BCE Loss: 0.05867
Epoch [3/10] - Training Logit BCE Loss: 0.05312
Epoch [4/10] - Training Logit BCE Loss: 0.04828
Epoch [5/10] - Training Logit BCE Loss: 0.04320
Epoch [6/10] - Training Logit BCE Loss: 0.03480
Epoch [7/10] - Training Logit BCE Loss: 0.02815
Epoch [8/10] - Training Logit BCE Loss: 0.02303
Epoch [9/10] - Training Logit BCE Loss: 0.02948
Epoch [10/10] - Training Logit BCE Loss: 0.02272

🔒 Entering Validation Phase...
➡️ Final Out-of-Sample Test Logit BCE Loss: 0.00950
➡️ Total Classification Accuracy: 99.50%

✨ Process finished cleanly. Run this exact setup for Burst instances.

In [ ]:
torch.save(model.state_dict(), 'hybrid_qnn_model_burst_pressure_flow_temperature.pth')